// This contains the typescript code for the component
// It defines several things Angular needs to know about the component
import { Component } from '@angular/core'; // Give me access to basic Angular features
import { RouterOutlet } from '@angular/router'; // Give me access to the Angular router


// @ Component identifies the attributes/characteristics of the component
@Component({
  // Selector is the tag-name used in the HTML to reference the component
  selector: 'app-root', // Where to insert the HTML generated by Angular for components
  imports: [RouterOutlet],
  templateUrl: './app.component.html', // Name of the html for the component (content of component)
  styleUrl: './app.component.css' // Name of the css file for component (styling of component)
})

// export allows other processes outside of this TypeScript file (like Angular) to access stuff in the TypeScript
export class AppComponent { // The class name is used in import statements to reference the data/methods in this export
  title = 'myFirstAngularApp';
}
