using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SampleOOPApplication
{

    /**************************************************************************************
     * This class will represent a person
     * 
     * Attributes: Name
     *             Height
     *             Weight
     *             Age
     *             Gender
     *             EyeColor
     *             HairColor
     *************************************************************************************/
    internal class Person
    {

        /**********************************************************************************
         * Instance Variables
         * 
         * 
         * 
         * ******************************************************************************/
         

        private string _name;
        private int _heightInInches;
        private double _weightInPounds;
        private int _age;
        private string _gender;
        private string _eyeColor;
        private string _hairColor;


        /********************************************************************************
         * Properties
         * *****************************************************************************/
        public string Name { get => _name; set => _name = value; }
        public int HeightInInches { get => _heightInInches; set => _heightInInches = value; }
        public double WeightInPounds { get => _weightInPounds; set => _weightInPounds = value; }
        public int Age { get => _age; set => _age = value; }
        public string Gender { get => _gender; set => _gender = value; }
        public string EyeColor { get => _eyeColor; set => _eyeColor = value; }
        public string HairColor { get => _hairColor; set => _hairColor = value; }


        /********************************************************************************
         * Constructors - Initialize objects of the class
         * *****************************************************************************/
        public Person(string name, int heightInInches, double weightInPounds, int age, string gender, string eyeColor, string hairColor)
        {
            _name = name;
            _heightInInches = heightInInches;
            _weightInPounds = weightInPounds;
            _age = age;
            _gender = gender;
            _eyeColor = eyeColor;
            _hairColor = hairColor;
        }

        /*******************************************************************************
         * Method Overrides
         * 
         * DO NOT ACCEPT THE CODE GENERATED BY AN IDE FOR THESE WITHOUT LOOKING AT IT
         * ****************************************************************************/
        public override bool Equals(object? obj)
        {
            return base.Equals(obj);
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override string? ToString()
        {
            return $"{Name} {HeightInInches} {Gender} {Age} years old";
        }
    }
}
