// Generated by the ng generate component command
// It has the basic/starter code for a component
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-student-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './student-list.component.html',
  styleUrl: './student-list.component.css'
})
// The export contains data and functions used by the html for the component
export class StudentListComponent {

  roster: any[] = [
    {name: "Youssef"},
    {name: "Zach"},
    {name: "Henrik"},
    {name: "Kiana"},
    {name: "Ravyn"},
    {name: "Amber"}
  ]
}
