package com.Server.dao;

import com.Server.model.Pet;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class PetServiceImplementation implements IPet{

    PetRepository thePetRepository; // Reference to repository

    // constructor - Generated by IDE - Note it automatically includes the reference to the repository
    //                                  a repository object will be instantiated and passed to the ctor
    @Autowired
    public PetServiceImplementation(PetRepository thePetRepository) {
        this.thePetRepository = thePetRepository;
    }

    @Override
    public List<Pet> getAllPets() {
        return thePetRepository.findAll();
    }

    @Override
    public Optional<Pet> returnPet(int petId) {
        return thePetRepository.findById(petId);
    }

    @Override
    @Transactional
    public Pet addPet(Pet aPet) {
        return thePetRepository.save(aPet);
    }

    @Override
    @Transactional
    public Pet updatePet(Pet aPet) {
        return thePetRepository.save(aPet);
    }

    @Override
    @Transactional
    public void deletePet(int petId) {
        thePetRepository.deleteById(petId);
    }
}
