package com.Server.controller;


import com.Server.dao.PetServiceImplementation;
import com.Server.model.Pet;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController // Tells the server there are controller methods in here for some of the URL paths
@RequestMapping("v1") // Use a prefix for all URL paths to indicate the version of the controller

public class PetApiController {
    PetServiceImplementation thePetService; //Define a reference to the Service to interact with data framework

    // Constructor - Generated by IDE with service reference which will be dependency injected
    public PetApiController(PetServiceImplementation thePetService) {
        this.thePetService = thePetService;
    }

    // Controller to return all the pets in the data source
    @GetMapping("/pets")
    public List<Pet> allPets(){
        return thePetService.getAllPets();
    }


}
